import pytest
import textwrap

from main1 import solve

def test_sample1():
  sample_input = textwrap.dedent("""
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """).strip()

  assert solve(sample_input) == 374

def test_sample_single():
  sample_input = textwrap.dedent("""
    ...#......
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ........#.
    """).strip()

  assert solve(sample_input) == 26
